"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PostTerminalSignatureRequestBodyJson(object):
    """Implementation of the 'PostTerminalSignatureRequestBodyJson' model.

    Attributes:
        signature (str): The model property of type str.
        transaction_id (uuid|str): The model property of type uuid|str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "signature": "signature",
        "transaction_id": "transaction_id",
    }

    _optionals = [
        "signature",
        "transaction_id",
    ]

    def __init__(
        self,
        signature=APIHelper.SKIP,
        transaction_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PostTerminalSignatureRequestBodyJson instance."""
        # Initialize members of the class
        if signature is not APIHelper.SKIP:
            self.signature = signature
        if transaction_id is not APIHelper.SKIP:
            self.transaction_id = transaction_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        signature =\
            dictionary.get("signature")\
            if dictionary.get("signature")\
                else APIHelper.SKIP
        transaction_id =\
            dictionary.get("transaction_id")\
            if dictionary.get("transaction_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(signature,
                   transaction_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _signature=(
            self.signature
            if hasattr(self, "signature")
            else None
        )
        _transaction_id=(
            self.transaction_id
            if hasattr(self, "transaction_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"signature={_signature!r}, "
            f"transaction_id={_transaction_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _signature=(
            self.signature
            if hasattr(self, "signature")
            else None
        )
        _transaction_id=(
            self.transaction_id
            if hasattr(self, "transaction_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"signature={_signature!s}, "
            f"transaction_id={_transaction_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
