"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PostVerificationRequestBodyJson(object):
    """Implementation of the 'PostVerificationRequestBodyJson' model.

    Attributes:
        payment_method_id (uuid|str): The model property of type uuid|str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_method_id": "payment_method_id",
    }

    _optionals = [
        "payment_method_id",
    ]

    def __init__(
        self,
        payment_method_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PostVerificationRequestBodyJson instance."""
        # Initialize members of the class
        if payment_method_id is not APIHelper.SKIP:
            self.payment_method_id = payment_method_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_method_id =\
            dictionary.get("payment_method_id")\
            if dictionary.get("payment_method_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(payment_method_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _payment_method_id=(
            self.payment_method_id
            if hasattr(self, "payment_method_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"payment_method_id={_payment_method_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _payment_method_id=(
            self.payment_method_id
            if hasattr(self, "payment_method_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"payment_method_id={_payment_method_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
