"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PostPaymentMethodTokenRequestBodyJson(object):
    """Implementation of the 'PostPaymentMethodTokenRequestBodyJson' model.

    Attributes:
        token (str): The model property of type str.
        customer_id (uuid|str): The model property of type uuid|str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "token": "token",
        "customer_id": "customer_id",
    }

    _optionals = [
        "token",
        "customer_id",
    ]

    def __init__(
        self,
        token=APIHelper.SKIP,
        customer_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PostPaymentMethodTokenRequestBodyJson instance."""
        # Initialize members of the class
        if token is not APIHelper.SKIP:
            self.token = token
        if customer_id is not APIHelper.SKIP:
            self.customer_id = customer_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        token =\
            dictionary.get("token")\
            if dictionary.get("token")\
                else APIHelper.SKIP
        customer_id =\
            dictionary.get("customer_id")\
            if dictionary.get("customer_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(token,
                   customer_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _customer_id=(
            self.customer_id
            if hasattr(self, "customer_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"token={_token!r}, "
            f"customer_id={_customer_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _token=(
            self.token
            if hasattr(self, "token")
            else None
        )
        _customer_id=(
            self.customer_id
            if hasattr(self, "customer_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"token={_token!s}, "
            f"customer_id={_customer_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
