"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PostSendLaterRequestBodyJson(object):
    """Implementation of the 'PostSendLaterRequestBodyJson' model.

    Attributes:
        send_at (datetime): The model property of type datetime.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "send_at": "send_at",
    }

    _optionals = [
        "send_at",
    ]

    def __init__(
        self,
        send_at=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PostSendLaterRequestBodyJson instance."""
        # Initialize members of the class
        if send_at is not APIHelper.SKIP:
            self.send_at =\
                 APIHelper.apply_datetime_converter(
                send_at, APIHelper.RFC3339DateTime)\
                 if send_at else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        send_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("send_at")).datetime\
            if dictionary.get("send_at") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(send_at,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _send_at=(
            self.send_at
            if hasattr(self, "send_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"send_at={_send_at!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _send_at=(
            self.send_at
            if hasattr(self, "send_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"send_at={_send_at!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
