"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PostInvoiceManualPaymentRequestBodyJson(object):
    """Implementation of the 'PostInvoiceManualPaymentRequestBodyJson' model.

    Attributes:
        total (float): The model property of type float.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "total": "total",
    }

    _optionals = [
        "total",
    ]

    def __init__(
        self,
        total=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PostInvoiceManualPaymentRequestBodyJson instance."""
        # Initialize members of the class
        if total is not APIHelper.SKIP:
            self.total = total

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        total =\
            dictionary.get("total")\
            if dictionary.get("total")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(total,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"total={_total!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"total={_total!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
