"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PostInvoiceManualPaymentMethod(object):
    """Implementation of the 'PostInvoiceManualPaymentMethod' enum.

    Attributes:
        CASH: The enum member of type str.
        CHECK: The enum member of type str.
        GIFTCARD: The enum member of type str.
        PAYPAL: The enum member of type str.
        VENMO: The enum member of type str.
        PAYPAL_BNPL: The enum member of type str.

    """

    CASH = "cash"

    CHECK = "check"

    GIFTCARD = "giftcard"

    PAYPAL = "paypal"

    VENMO = "venmo"

    PAYPAL_BNPL = "paypal_bnpl"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
