"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PostFileRequestBody(object):
    """Implementation of the 'PostFileRequestBody' model.

    Attributes:
        file (binary): The model property of type binary.
        tag (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "file": "file",
        "tag": "tag",
    }

    _optionals = [
        "file",
        "tag",
    ]

    def __init__(
        self,
        file=APIHelper.SKIP,
        tag=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PostFileRequestBody instance."""
        # Initialize members of the class
        if file is not APIHelper.SKIP:
            self.file = file
        if tag is not APIHelper.SKIP:
            self.tag = tag

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        file =\
            dictionary.get("file")\
            if dictionary.get("file")\
                else APIHelper.SKIP
        tag =\
            dictionary.get("tag")\
            if dictionary.get("tag")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(file,
                   tag,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _file=(
            self.file
            if hasattr(self, "file")
            else None
        )
        _tag=(
            self.tag
            if hasattr(self, "tag")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"file={_file!r}, "
            f"tag={_tag!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _file=(
            self.file
            if hasattr(self, "file")
            else None
        )
        _tag=(
            self.tag
            if hasattr(self, "tag")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"file={_file!s}, "
            f"tag={_tag!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
