"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PutSendInvoiceBulkRequestBodyJson(object):
    """Implementation of the 'PutSendInvoiceBulkRequestBodyJson' model.

    Attributes:
        invoice_ids (List[uuid|str]): The model property of type List[uuid|str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "invoice_ids": "invoice_ids",
    }

    _optionals = [
        "invoice_ids",
    ]

    def __init__(
        self,
        invoice_ids=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PutSendInvoiceBulkRequestBodyJson instance."""
        # Initialize members of the class
        if invoice_ids is not APIHelper.SKIP:
            self.invoice_ids = invoice_ids

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        invoice_ids =\
            dictionary.get("invoice_ids")\
            if dictionary.get("invoice_ids")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(invoice_ids,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _invoice_ids=(
            self.invoice_ids
            if hasattr(self, "invoice_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"invoice_ids={_invoice_ids!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _invoice_ids=(
            self.invoice_ids
            if hasattr(self, "invoice_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"invoice_ids={_invoice_ids!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
