"""staxfattmerchantapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from staxfattmerchantapi.api_helper import APIHelper


class PutNotifyEmailRequestBodyJson(object):
    """Implementation of the 'PutNotifyEmailRequestBodyJson' model.

    Attributes:
        email (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email": "email",
    }

    _optionals = [
        "email",
    ]

    def __init__(
        self,
        email=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PutNotifyEmailRequestBodyJson instance."""
        # Initialize members of the class
        if email is not APIHelper.SKIP:
            self.email = email

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(email,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email={_email!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email={_email!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
